[versions]
com-destroystokyo-paper-paper-api = "1.12.2-R0.1-SNAPSHOT"
com-github-ben-manes-caffeine-caffeine = "2.9.3"
com-github-thatsmusic99-configurationmaster-api = "v2.0.0-rc.1"
com-google-code-findbugs-jsr305 = "3.0.2"
com-ibm-icu-icu4j = "74.2"
me-clip-placeholderapi = "2.11.6"
me-xdrop-fuzzywuzzy = "1.4.0"
net-kyori-adventure-platform-bukkit = "4.3.3"
net-kyori-adventure-text-minimessage = "4.17.0"
net-kyori-adventure-text-serializer-gson = "4.17.0"
org-bstats-bstats-bukkit = "3.0.2"
org-projectlombok-lombok = "1.18.34"

[libraries]
com-destroystokyo-paper-paper-api = { module = "com.destroystokyo.paper:paper-api", version.ref = "com-destroystokyo-paper-paper-api" }
com-github-ben-manes-caffeine-caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "com-github-ben-manes-caffeine-caffeine" }
com-github-thatsmusic99-configurationmaster-api = { module = "com.github.thatsmusic99:ConfigurationMaster-API", version.ref = "com-github-thatsmusic99-configurationmaster-api" }
com-google-code-findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "com-google-code-findbugs-jsr305" }
com-ibm-icu-icu4j = { module = "com.ibm.icu:icu4j", version.ref = "com-ibm-icu-icu4j" }
me-clip-placeholderapi = { module = "me.clip:placeholderapi", version.ref = "me-clip-placeholderapi" }
me-xdrop-fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "me-xdrop-fuzzywuzzy" }
net-kyori-adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "net-kyori-adventure-platform-bukkit" }
net-kyori-adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "net-kyori-adventure-text-minimessage" }
net-kyori-adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "net-kyori-adventure-text-serializer-gson" }
org-bstats-bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "org-bstats-bstats-bukkit" }
org-projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "org-projectlombok-lombok" }
